[features]
seeds = true
[programs.devnet]
fbnx_amm = "FzbA7oybquXL6sNn71hPU2RQh1kbRiDtCGbwmk34VFR2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/User/sol-twitter/target/deploy/sol_twitter-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
